name: minio
description: Unofficial MinIO Dart Client SDK that provides simple APIs to access any Amazon S3 compatible object storage server.
version: 1.3.0
homepage: https://github.com/xtyxtyx/minio-dart
issue_tracker: https://github.com/xtyxtyx/minio-dart/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  http: ^0.13.0-nullsafety.0
  crypto: ^3.0.0
  convert: ^3.0.0-nullsafety.0
  xml: ^5.0.0-nullsafety.1
  buffer: ^1.1.0-nullsafety.0
  intl: ^0.17.0-nullsafety.2
  mime: ^1.0.0-nullsafety.0
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.19
  html: ^0.15.0-nullsafety.0 
