name: minio
description: Unofficial MinIO Dart Client SDK that provides simple APIs to access any Amazon S3 compatible object storage server.
version: 1.3.0
homepage: https://github.com/xtyxtyx/minio-dart
issue_tracker: https://github.com/xtyxtyx/minio-dart/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta:
  http:
  crypto:
  convert:
  xml:
  buffer:
  intl:
  mime:
  path:

dev_dependencies:
  pedantic:
  test:
  html:
